import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { kickFalsa, T } from '../falsa.mjs';
const SITE = new URL('../../site/', import.meta.url).pathname;
const tipos = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' };
const srv = http.createServer((req, res) => {
  const c = req.url.split('?')[0];
  const f = path.join(SITE, c === '/' ? 'index.html' : c);
  if (!f.startsWith(SITE) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); return res.end(); }
  res.writeHead(200, { 'content-type': tipos[path.extname(f)] || 'text/plain' }); res.end(fs.readFileSync(f));
});
await new Promise((ok) => srv.listen(0, '127.0.0.1', ok));
const nav = await chromium.launch({ executablePath: process.env.DETETIVE_CHROME });
const p = await nav.newPage({ viewport: { width: 1440, height: 900 }, locale: 'pt-PT' });
p.setDefaultTimeout(8000);
p.on('pageerror', (e) => console.log('ERRO', e.message));
await p.addInitScript(() => { try { localStorage.setItem('replay.idioma', 'pt'); } catch {} });
await kickFalsa(p, { canais: ['tchubi', 'outro'] });
await p.goto(`http://127.0.0.1:${srv.address().port}/`, { waitUntil: 'networkidle' });
await p.fill('#canais', 'tchubi\noutro');
await p.click('#carregar');
await p.waitForSelector('.tile', { timeout: 15000 });
const passo = async (n, f) => { try { await f(); console.log('ok', n); } catch (e) { console.log('FALHOU', n, e.message.split('\n').slice(0, 6).join(' | ')); } };
await passo('nome', () => p.click('#faixas button.nome[data-quem="tchubi"]'));
await passo('chat', () => p.click('#escolherChat'));
await passo('trecho', () => p.click('#escolherTrecho'));
await passo('alca', async () => { await p.locator('#alcaInicio').focus(); await p.keyboard.press('Home'); });
await passo('outro', () => p.click('#faixas button.nome[data-quem="outro"]'));
await passo('usar', () => p.click('#usarTrecho'));
await passo('ler', () => p.click('#lerChatTrecho'));
await p.waitForTimeout(3000);
console.log(await p.locator('#estadoChatTrecho').innerText(), '|', await p.locator('#acoesResumo').innerText());
await nav.close(); srv.close();
